name: flutter_webp
description: Flutter plugin for converting (encoding) images to webp format.
version: 0.2.2
homepage: https://github.com/nucleartux/flutter_webp

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.9-pre.94 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutterwebp
        pluginClass: FlutterWebpPlugin
